---
server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      force-response: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mingyuchoo: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE

spring:
  output:
    ansi:
      enabled: DETECT
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type: trace
  data:
    rest:
      base-path: /api # for HAL Explorer