---
server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mingyuchoo: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE

spring:
  output:
    ansi:
      enabled: DETECT
  security:
    user:
      name: admin
      password: admin
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true

sql:
  schema: schema.sql
  data: data.sql

