---
server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      force-response: true

spring:
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  output:
    ansi.enabled: always
  jpa:
    hibernate:
      show-sql: true
      use_sql_comments: true
      format_sql: true
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  playground:
    enabled: true
    pageTitle: Playground
    mapping: /graphql
    endpoint:
      graphql: /graphql
    static:
      basePath: /
