DELETE FROM PERSON;
DELETE FROM ITEM;
DELETE FROM CART;

INSERT INTO CART(ID, NAME, PAID) VALUES (1, '식량', true);
INSERT INTO CART(ID, NAME, PAID) VALUES (2, '의류', true);
INSERT INTO CART(ID, NAME, PAID) VALUES (3, '가전', false);

INSERT INTO ITEM(ID, NAME, PRICE, CART_ID) VALUES (1, '쌀', 10, 1);
INSERT INTO ITEM(ID, NAME, PRICE, CART_ID) VALUES (2, '속옷', 60, 2);
INSERT INTO ITEM(ID, NAME, PRICE, CART_ID) VALUES (3, '바지', 100, 2);
INSERT INTO ITEM(ID, NAME, PRICE, CART_ID) VALUES (4, '세탁기', 7000, 3);
INSERT INTO ITEM(ID, NAME, PRICE, CART_ID) VALUES (5, '냉장고', 5400, 3);
INSERT INTO ITEM(ID, NAME, PRICE, CART_ID) VALUES (6, 'TV', 3200, 3);

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (1, '부솔', '최');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (2, '가인', '김');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (3, '노들', '강');
