version: "3.8"
services:
  postgresql-db:
    image: "postgres:latest"
    container_name: postgresql-db
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
