version: "3.9"

# Create `db_net` if exists use it
networks:
  db_net:
    name: db_net
    driver: bridge

# Use `db_net`
# networks:
#   default:
#     external: true
#     name: db_net

volumes:
  db_data:

services:
  postgresql-db:
    image: postgres:latest
    container_name: postgresql-db
    ports:
      - 5432:5432
    networks:
      - db_net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SONAR_DB=sonar
      - SONAR_USER=sonar
      - SONAR_PASSWORD=sonar
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./db_data:/var/lib/postgresql/data