---
server:
  port: 4000
  servlet:
    encoding:
      force-response: true

logging:
  level:
    root: ERROR

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
  playground:
    enabled: true
    pageTitle: Playground
    mapping: /graphql
    endpoint:
      graphql: /graphql
    static:
      basePath: /

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mariadb://localhost:3306/root
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  output:
    ansi.enabled: always
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      use_sql_comments: true
      format_sql: true

