---
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  output:
    ansi:
      enabled: DETECT

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type: trace

  data:
    rest:
      basePath: /api
      # defaultMediaType: application/json

logging:
  file: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.mingyuchoo: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE
