#!/bin/sh
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $SONAR_USER WITH PASSWORD '$SONAR_PASSWORD';
  CREATE DATABASE $SONAR_DB;
  GRANT USAGE ON SCHEMA public TO $SONAR_USER;
  GRANT ALL PRIVILEGES ON DATABASE $SONAR_DB TO $SONAR_USER;
EOSQL
